# Dockerfile using stable Maxfuzz image
FROM everestmz/maxfuzz:latest

WORKDIR /root/fuzzer-files
COPY ./* ./
COPY ./.git .
RUN chmod -R 755 /root/fuzzer-files
RUN echo "export GIT_SHA=$(git rev-parse HEAD)" >> /root/fuzzer-files/base/environment
