# CircleCI Golang 1.9 config file
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9 
    working_directory: /go/src/maxfuzz/fuzzer-base/
    steps:
      - checkout:
          path: /go/src/maxfuzz
      - run: pwd
      - run: echo $GOPATH
      - run: ls
      - run: curl -L -s https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64 -o /go/bin/dep && chmod +x /go/bin/dep
      - run: make
      - run: make test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
