#!/bin/bash
if [[ -z "$GIT_SHA" ]];
then echo "GIT_SHA ENV var is null" && exit 1
fi
if [ "$1" = "reproduce" ]; then
  echo "Running $FUZZER_NAME reproducer, revision $GIT_SHA"
else
  echo "Running fuzzer $FUZZER_NAME, revision $GIT_SHA"
fi
$BUILD_FILES/build_steps
if [ "$1" = "reproduce" ]; then
  MAXFUZZ_ENV=reproducer ASAN_OPTIONS="symbolize=1:detect_leaks=0:abort_on_error=1" $GOBIN/reproduce
elif [ "$1" = "gofuzz" ]; then
  $GOBIN/pre-sync
  MAXFUZZ_ENV=fuzzer $GOBIN/go-monitor
else
  $GOBIN/pre-sync
  MAXFUZZ_ENV=fuzzer AFL_IO_OPTIONS=$(cat /root/config/afl-io-options) $GOBIN/monitor
fi
